#!/bin/bash

HTML_PATH='./site.html'
URL='https://www.archlinux.org/'

no_update=false
check_only=false
dry_run=false

while test $# != 0
do
    case $1 in
	-n | --no-update) no_update=true;;
	-c | --check-only) check_only=true;;
	-d | --dry-run) no_update=true
			check_only=true;;
	*) printf "Invalid flag %s\n" $1
	   exit 1;;
    esac
    shift
done

if [ ! -f $HTML_PATH ]
then
    printf 'Local copy of site not found.\n'
    printf 'Downloading from %s and saving to %s\n\n' $URL $HTML_PATH

    wget -O $HTML_PATH $URL

    exit 1
fi

printf 'Downloading %s\n' $URL

wget --quiet -O /tmp/temp.html $URL

comp=$(python compare_html.py "$(cat $HTML_PATH)" "$(cat /tmp/temp.html)")

if [ $? -eq 1 ]
then
    printf 'An error occurred, quiting.\n'
    exit 1
fi


case $comp in
    0) printf 'No changes found, safe to update.\n'

       if [ $no_update = true ]
       then
	   printf 'Exiting without updating.\n'
	   exit 0
       fi
              
       printf 'Running pacman...\n\n'
       sudo pacman -Syu;;

    
    -1) printf 'Changes found, check website before next update.\n'

	if [ $check_only = false ]
	then
	    printf 'Writing page from %s to %s.\n' $URL $HTML_PATH
	    cp /tmp/temp.html $HTML_PATH
	fi;;
	
esac
